//
//  PlaceData.swift
//  MyLearning
//
//  Created by Hien Nguyen on 5/11/18.
//  Copyright © 2018 Quang Dang N.K. All rights reserved.
//

import Foundation
var placesData = [
    Place(nameCity: "Rome",imageName : #imageLiteral(resourceName: "Rome"),addressCity: "Italy", description: "Rome, Italy’s capital, is a sprawling, cosmopolitan city with nearly 3,000 years of globally influential art, architecture and culture on display. Ancient ruins such as the Forum and the Colosseum evoke the power of the former Roman Empire", rate: "9/10", listImage: [#imageLiteral(resourceName: "rome 1"),#imageLiteral(resourceName: "rome 2"),#imageLiteral(resourceName: "rome 3"),#imageLiteral(resourceName: "rome 4")]),
    Place(nameCity: "Venice",imageName : #imageLiteral(resourceName: "Venice"),addressCity: "Italy", description: "Venice, the capital of northern Italy’s Veneto region, is built on more than 100 small islands in a lagoon in the Adriatic Sea. It has no roads, just canals – including the Grand Canal thoroughfare – lined with Renaissance and Gothic palaces", rate: "9/10",listImage: [#imageLiteral(resourceName: "Venice 1"),#imageLiteral(resourceName: "Venice 2"),#imageLiteral(resourceName: "Venice 3"),#imageLiteral(resourceName: "Venice 4")]),
    Place(nameCity: "Sapa",imageName : #imageLiteral(resourceName: "Photo2"),addressCity: "Vietnam", description: "Sa Pa is a town in the Hoàng Liên Son Mountains of northwestern Vietnam. A popular trekking base, it overlooks the terraced rice fields of the Muong Hoa Valley, and is near the 3,143m-tall Phang Xi Pang peak, which is climbable via a steep, multiday guided walk", rate: "9/10", listImage:[#imageLiteral(resourceName: "Sapa 1"),#imageLiteral(resourceName: "Sapa 2"),#imageLiteral(resourceName: "Sapa 3"),#imageLiteral(resourceName: "Sapa 4")]),
    Place(nameCity: "Moscow",imageName : #imageLiteral(resourceName: "Moscow 2-1"), addressCity: "Russia", description: "Moscow, on the Moskva River in western Russia, is the nation’s cosmopolitan capital. In its historic core is the Kremlin, a complex that’s home to the president and tsarist treasures in the Armoury", rate: "7.5/10", listImage: [#imageLiteral(resourceName: "Moscow 1"),#imageLiteral(resourceName: "Moscow 2"),#imageLiteral(resourceName: "Moscow 3"),#imageLiteral(resourceName: "Moscow 4")]),
    Place(nameCity: "Budapest",imageName : #imageLiteral(resourceName: "Budapest"), addressCity: "Hungary", description: "Budapest, Hungary’s capital, is bisected by the River Danube. Its 19th-century Chain Bridge connects the hilly Buda district with flat Pest. A funicular runs up Castle Hill to Buda’s Old Town, where the Budapest History Museum traces city life from Roman times onward", rate: "7.5/10", listImage: [#imageLiteral(resourceName: "Budapest 1"),#imageLiteral(resourceName: "Budapest 2"),#imageLiteral(resourceName: "Budapest 3"),#imageLiteral(resourceName: "Budapest 4")]),
    Place(nameCity: "London",imageName : #imageLiteral(resourceName: "London"),addressCity: "England", description: "London, the capital of England and the United Kingdom, is a 21st-century city with history stretching back to Roman times. At its centre stand the imposing Houses of Parliament, the iconic ‘Big Ben’ clock tower and Westminster Abbey, site of British monarch coronations", rate: "8/10", listImage: [#imageLiteral(resourceName: "London 1"),#imageLiteral(resourceName: "London 2"),#imageLiteral(resourceName: "London 3"),#imageLiteral(resourceName: "London 4")]),
    Place(nameCity: "Arches National Park",imageName :#imageLiteral(resourceName: "Photo-1"),addressCity: "USA", description: "Utah is home to some of the world’s most magical natural landmarks. Monument Valley, Bryce NP, Zion NP, Canyonlands NP… I could fill half of this list of amazing travel destinations without ever leaving the state of Utah, but if I have to choose just one, it would be the Arches National Park. And the absolute must-do in the park is the Delicate Arch Trail!", rate: "3/10", listImage: [#imageLiteral(resourceName: "Sahara 1"),#imageLiteral(resourceName: "Sahara 2"),#imageLiteral(resourceName: "Sahara 3"),#imageLiteral(resourceName: "Sahara 4")]),
]
